use bevy::prelude::*;

use super::theme_data::Contrast;

#[derive(Clone, Copy, Debug)]
pub enum Surface {
    Background,
    Surface,
    SurfaceVariant,
    SurfaceDim,
    SurfaceBright,
    InverseSurface,
}

#[derive(Clone, Copy, Debug)]
pub enum Accent {
    Primary,
    PrimaryFixed,
    PrimaryFixedDim,
    InversePrimary,
    Secondary,
    SecondaryFixed,
    SecondaryFixedDim,
    Tertiary,
    TertiaryFixed,
    TertiaryFixedDim,
    Error,
    Outline,
    OutlineVariant,
    Shadow,
    Scrim,
}

#[derive(Clone, Copy, Debug)]
pub enum Container {
    Primary,
    Secondary,
    Tertiary,
    Error,
    SurfaceLowest,
    SurfaceLow,
    SurfaceMid,
    SurfaceHigh,
    SurfaceHighest,
}

#[derive(Clone, Copy, Debug)]
pub enum On {
    Primary,
    PrimaryContainer,
    PrimaryFixed,
    PrimaryFixedVariant,
    Secondary,
    SecondaryContainer,
    SecondaryFixed,
    SecondaryFixedVariant,
    Tertiary,
    TertiaryContainer,
    TertiaryFixed,
    TertiaryFixedVariant,
    Error,
    ErrorContainer,
    Background,
    Surface,
    SurfaceVariant,
    InverseSurface,
}

#[derive(Clone, Debug, Default, Reflect)]
pub struct ExtendedColor {
    pub name: String,
    pub color: Color,
    pub description: String,
    pub harmonized: bool,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct CoreColors {
    pub primary: Color,
    pub secondary: Option<Color>,
    pub tertiary: Option<Color>,
    pub error: Option<Color>,
    pub neutral: Option<Color>,
    pub neutral_variant: Option<Color>,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct SchemeColors {
    pub primary: Color,
    pub on_primary: Color,
    pub primary_container: Color,
    pub on_primary_container: Color,
    pub secondary: Color,
    pub on_secondary: Color,
    pub secondary_container: Color,
    pub on_secondary_container: Color,
    pub tertiary: Color,
    pub on_tertiary: Color,
    pub tertiary_container: Color,
    pub on_tertiary_container: Color,
    pub error: Color,
    pub on_error: Color,
    pub error_container: Color,
    pub on_error_container: Color,
    pub background: Color,
    pub on_background: Color,
    pub surface: Color,
    pub on_surface: Color,
    pub surface_variant: Color,
    pub on_surface_variant: Color,
    pub outline: Color,
    pub outline_variant: Color,
    pub shadow: Color,
    pub scrim: Color,
    pub inverse_surface: Color,
    pub inverse_on_surface: Color,
    pub inverse_primary: Color,
    pub primary_fixed: Color,
    pub on_primary_fixed: Color,
    pub primary_fixed_dim: Color,
    pub on_primary_fixed_variant: Color,
    pub secondary_fixed: Color,
    pub on_secondary_fixed: Color,
    pub secondary_fixed_dim: Color,
    pub on_secondary_fixed_variant: Color,
    pub tertiary_fixed: Color,
    pub on_tertiary_fixed: Color,
    pub tertiary_fixed_dim: Color,
    pub on_tertiary_fixed_variant: Color,
    pub surface_dim: Color,
    pub surface_bright: Color,
    pub surface_container_lowest: Color,
    pub surface_container_low: Color,
    pub surface_container: Color,
    pub surface_container_high: Color,
    pub surface_container_highest: Color,
}

impl SchemeColors {
    pub fn surface(&self, surface: Surface) -> Color {
        match surface {
            Surface::Background => self.background,
            Surface::Surface => self.surface,
            Surface::InverseSurface => self.inverse_surface,
            Surface::SurfaceVariant => self.surface_variant,
            Surface::SurfaceDim => self.surface_dim,
            Surface::SurfaceBright => self.surface_bright,
        }
    }

    pub fn accent(&self, accent: Accent) -> Color {
        match accent {
            Accent::Primary => self.primary,
            Accent::PrimaryFixed => self.primary_fixed,
            Accent::PrimaryFixedDim => self.primary_fixed_dim,
            Accent::InversePrimary => self.inverse_primary,
            Accent::Secondary => self.secondary,
            Accent::SecondaryFixed => self.secondary_fixed,
            Accent::SecondaryFixedDim => self.secondary_fixed_dim,
            Accent::Tertiary => self.tertiary,
            Accent::TertiaryFixed => self.tertiary_fixed,
            Accent::TertiaryFixedDim => self.tertiary_fixed_dim,
            Accent::Error => self.error,
            Accent::Outline => self.outline,
            Accent::OutlineVariant => self.outline_variant,
            Accent::Shadow => self.shadow,
            Accent::Scrim => self.scrim,
        }
    }

    pub fn container(&self, container: Container) -> Color {
        match container {
            Container::Primary => self.primary_container,
            Container::Secondary => self.secondary_container,
            Container::Tertiary => self.tertiary_container,
            Container::Error => self.error_container,
            Container::SurfaceLowest => self.surface_container_lowest,
            Container::SurfaceLow => self.surface_container_low,
            Container::SurfaceMid => self.surface_container,
            Container::SurfaceHigh => self.surface_container_high,
            Container::SurfaceHighest => self.surface_container_highest,
        }
    }

    pub fn on(&self, on: On) -> Color {
        match on {
            On::Primary => self.on_primary,
            On::PrimaryContainer => self.on_primary_container,
            On::PrimaryFixed => self.on_primary_fixed,
            On::PrimaryFixedVariant => self.on_primary_fixed_variant,
            On::Secondary => self.on_secondary,
            On::SecondaryContainer => self.on_secondary_container,
            On::SecondaryFixed => self.on_secondary_fixed,
            On::SecondaryFixedVariant => self.on_secondary_fixed_variant,
            On::Tertiary => self.on_tertiary,
            On::TertiaryContainer => self.on_tertiary_container,
            On::TertiaryFixed => self.on_tertiary_fixed,
            On::TertiaryFixedVariant => self.on_tertiary_fixed_variant,
            On::Error => self.on_error,
            On::ErrorContainer => self.on_error_container,
            On::Background => self.on_background,
            On::Surface => self.on_surface,
            On::SurfaceVariant => self.on_surface_variant,
            On::InverseSurface => self.inverse_on_surface,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorScheme {
    pub colors: SchemeColors,
    pub medium_contrast: SchemeColors,
    pub high_contrast: SchemeColors,
}

impl ColorScheme {
    pub fn contrast(&self, contrast: Contrast) -> SchemeColors {
        match contrast {
            Contrast::Standard => self.colors,
            Contrast::Medium => self.medium_contrast,
            Contrast::High => self.high_contrast,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorSchemes {
    pub light: ColorScheme,
    pub dark: ColorScheme,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorPalette {
    pub p_0: Color,
    pub p_5: Color,
    pub p_10: Color,
    pub p_15: Color,
    pub p_20: Color,
    pub p_25: Color,
    pub p_30: Color,
    pub p_35: Color,
    pub p_40: Color,
    pub p_50: Color,
    pub p_60: Color,
    pub p_70: Color,
    pub p_80: Color,
    pub p_90: Color,
    pub p_95: Color,
    pub p_98: Color,
    pub p_99: Color,
    pub p_100: Color,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorPalettes {
    pub primary: ColorPalette,
    pub secondary: ColorPalette,
    pub tertiary: ColorPalette,
    pub neutral: ColorPalette,
    pub neutral_variant: ColorPalette,
}

// TODO: write asset loader for theme colors and load it from a material-theme.json
/// Loosly Follows Material3 theme format
#[derive(Clone, Debug, Reflect)]
pub struct ThemeColors {
    pub description: String,
    // TODO: Generate colors from seed & core colors?
    pub seed: Color,
    pub core_colors: CoreColors,
    pub extended_colors: Vec<ExtendedColor>,
    pub schemes: ColorSchemes,
    pub palettes: ColorPalettes,
}

impl Default for ThemeColors {
    fn default() -> Self {
        Self {
            description: "Sickle UI Theme".into(),
            seed: Color::hex("037E90").unwrap(),
            core_colors: CoreColors {
                primary: Color::hex("BCB4A3").unwrap(),
                secondary: Color::hex("1A1A1A").unwrap().into(),
                neutral: Color::hex("262829").unwrap().into(),
                ..default()
            },
            extended_colors: Default::default(),
            schemes: ColorSchemes {
                light: ColorScheme {
                    colors: SchemeColors {
                        primary: Color::hex("8B4F24").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("FFDBC7").unwrap(),
                        on_primary_container: Color::hex("311300").unwrap(),
                        secondary: Color::hex("755846").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("FFDBC7").unwrap(),
                        on_secondary_container: Color::hex("2B1709").unwrap(),
                        tertiary: Color::hex("606134").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("E6E6AD").unwrap(),
                        on_tertiary_container: Color::hex("1C1D00").unwrap(),
                        error: Color::hex("BA1A1A").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("FFDAD6").unwrap(),
                        on_error_container: Color::hex("410002").unwrap(),
                        background: Color::hex("FFF8F5").unwrap(),
                        on_background: Color::hex("221A15").unwrap(),
                        surface: Color::hex("FFF8F5").unwrap(),
                        on_surface: Color::hex("221A15").unwrap(),
                        surface_variant: Color::hex("F4DED3").unwrap(),
                        on_surface_variant: Color::hex("52443C").unwrap(),
                        outline: Color::hex("FFD200").unwrap(),
                        outline_variant: Color::hex("D7C3B8").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("382E29").unwrap(),
                        inverse_on_surface: Color::hex("FFEDE5").unwrap(),
                        inverse_primary: Color::hex("FFB688").unwrap(),
                        primary_fixed: Color::hex("FFDBC7").unwrap(),
                        on_primary_fixed: Color::hex("311300").unwrap(),
                        primary_fixed_dim: Color::hex("FFB688").unwrap(),
                        on_primary_fixed_variant: Color::hex("6E380F").unwrap(),
                        secondary_fixed: Color::hex("FFDBC7").unwrap(),
                        on_secondary_fixed: Color::hex("2B1709").unwrap(),
                        secondary_fixed_dim: Color::hex("E5BFA9").unwrap(),
                        on_secondary_fixed_variant: Color::hex("5B4130").unwrap(),
                        tertiary_fixed: Color::hex("E6E6AD").unwrap(),
                        on_tertiary_fixed: Color::hex("1C1D00").unwrap(),
                        tertiary_fixed_dim: Color::hex("CACA93").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("48491E").unwrap(),
                        surface_dim: Color::hex("E7D7CE").unwrap(),
                        surface_bright: Color::hex("FFF8F5").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("FFF1EA").unwrap(),
                        surface_container: Color::hex("FCEBE2").unwrap(),
                        surface_container_high: Color::hex("F6E5DC").unwrap(),
                        surface_container_highest: Color::hex("F0DFD7").unwrap(),
                    },
                    medium_contrast: SchemeColors {
                        primary: Color::hex("69350B").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("A56538").unwrap(),
                        on_primary_container: Color::hex("FFFFFF").unwrap(),
                        secondary: Color::hex("573D2D").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("8D6E5B").unwrap(),
                        on_secondary_container: Color::hex("FFFFFF").unwrap(),
                        tertiary: Color::hex("44451B").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("777748").unwrap(),
                        on_tertiary_container: Color::hex("FFFFFF").unwrap(),
                        error: Color::hex("8C0009").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("DA342E").unwrap(),
                        on_error_container: Color::hex("FFFFFF").unwrap(),
                        background: Color::hex("FFF8F5").unwrap(),
                        on_background: Color::hex("221A15").unwrap(),
                        surface: Color::hex("FFF8F5").unwrap(),
                        on_surface: Color::hex("221A15").unwrap(),
                        surface_variant: Color::hex("F4DED3").unwrap(),
                        on_surface_variant: Color::hex("4E4038").unwrap(),
                        outline: Color::hex("FFD200").unwrap(),
                        outline_variant: Color::hex("88776E").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("382E29").unwrap(),
                        inverse_on_surface: Color::hex("FFEDE5").unwrap(),
                        inverse_primary: Color::hex("FFB688").unwrap(),
                        primary_fixed: Color::hex("A56538").unwrap(),
                        on_primary_fixed: Color::hex("FFFFFF").unwrap(),
                        primary_fixed_dim: Color::hex("884D22").unwrap(),
                        on_primary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed: Color::hex("8D6E5B").unwrap(),
                        on_secondary_fixed: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed_dim: Color::hex("735644").unwrap(),
                        on_secondary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed: Color::hex("777748").unwrap(),
                        on_tertiary_fixed: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed_dim: Color::hex("5E5E32").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        surface_dim: Color::hex("E7D7CE").unwrap(),
                        surface_bright: Color::hex("FFF8F5").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("FFF1EA").unwrap(),
                        surface_container: Color::hex("FCEBE2").unwrap(),
                        surface_container_high: Color::hex("F6E5DC").unwrap(),
                        surface_container_highest: Color::hex("F0DFD7").unwrap(),
                    },
                    high_contrast: SchemeColors {
                        primary: Color::hex("3B1800").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("69350B").unwrap(),
                        on_primary_container: Color::hex("FFFFFF").unwrap(),
                        secondary: Color::hex("321D0F").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("573D2D").unwrap(),
                        on_secondary_container: Color::hex("FFFFFF").unwrap(),
                        tertiary: Color::hex("232400").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("44451B").unwrap(),
                        on_tertiary_container: Color::hex("FFFFFF").unwrap(),
                        error: Color::hex("4E0002").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("8C0009").unwrap(),
                        on_error_container: Color::hex("FFFFFF").unwrap(),
                        background: Color::hex("FFF8F5").unwrap(),
                        on_background: Color::hex("221A15").unwrap(),
                        surface: Color::hex("FFF8F5").unwrap(),
                        on_surface: Color::hex("000000").unwrap(),
                        surface_variant: Color::hex("F4DED3").unwrap(),
                        on_surface_variant: Color::hex("2D211A").unwrap(),
                        outline: Color::hex("FFD200").unwrap(),
                        outline_variant: Color::hex("4E4038").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("382E29").unwrap(),
                        inverse_on_surface: Color::hex("FFFFFF").unwrap(),
                        inverse_primary: Color::hex("FFE7DB").unwrap(),
                        primary_fixed: Color::hex("69350B").unwrap(),
                        on_primary_fixed: Color::hex("FFFFFF").unwrap(),
                        primary_fixed_dim: Color::hex("4B2100").unwrap(),
                        on_primary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed: Color::hex("573D2D").unwrap(),
                        on_secondary_fixed: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed_dim: Color::hex("3E2718").unwrap(),
                        on_secondary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed: Color::hex("44451B").unwrap(),
                        on_tertiary_fixed: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed_dim: Color::hex("2E2E06").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        surface_dim: Color::hex("E7D7CE").unwrap(),
                        surface_bright: Color::hex("FFF8F5").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("FFF1EA").unwrap(),
                        surface_container: Color::hex("FCEBE2").unwrap(),
                        surface_container_high: Color::hex("F6E5DC").unwrap(),
                        surface_container_highest: Color::hex("F0DFD7").unwrap(),
                    },
                },
                dark: ColorScheme {
                    colors: SchemeColors {
                        primary: Color::hex("FFB688").unwrap(),
                        on_primary: Color::hex("512400").unwrap(),
                        primary_container: Color::hex("6E380F").unwrap(),
                        on_primary_container: Color::hex("FFDBC7").unwrap(),
                        secondary: Color::hex("E5BFA9").unwrap(),
                        on_secondary: Color::hex("432B1C").unwrap(),
                        secondary_container: Color::hex("5B4130").unwrap(),
                        on_secondary_container: Color::hex("FFDBC7").unwrap(),
                        tertiary: Color::hex("CACA93").unwrap(),
                        on_tertiary: Color::hex("32320A").unwrap(),
                        tertiary_container: Color::hex("48491E").unwrap(),
                        on_tertiary_container: Color::hex("E6E6AD").unwrap(),
                        error: Color::hex("FFB4AB").unwrap(),
                        on_error: Color::hex("690005").unwrap(),
                        error_container: Color::hex("93000A").unwrap(),
                        on_error_container: Color::hex("FFDAD6").unwrap(),
                        background: Color::hex("19120D").unwrap(),
                        on_background: Color::hex("F0DFD7").unwrap(),
                        surface: Color::hex("19120D").unwrap(),
                        on_surface: Color::hex("F0DFD7").unwrap(),
                        surface_variant: Color::hex("52443C").unwrap(),
                        on_surface_variant: Color::hex("D7C3B8").unwrap(),
                        outline: Color::hex("FFD200").unwrap(),
                        outline_variant: Color::hex("52443C").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("F0DFD7").unwrap(),
                        inverse_on_surface: Color::hex("382E29").unwrap(),
                        inverse_primary: Color::hex("8B4F24").unwrap(),
                        primary_fixed: Color::hex("FFDBC7").unwrap(),
                        on_primary_fixed: Color::hex("311300").unwrap(),
                        primary_fixed_dim: Color::hex("FFB688").unwrap(),
                        on_primary_fixed_variant: Color::hex("6E380F").unwrap(),
                        secondary_fixed: Color::hex("FFDBC7").unwrap(),
                        on_secondary_fixed: Color::hex("2B1709").unwrap(),
                        secondary_fixed_dim: Color::hex("E5BFA9").unwrap(),
                        on_secondary_fixed_variant: Color::hex("5B4130").unwrap(),
                        tertiary_fixed: Color::hex("E6E6AD").unwrap(),
                        on_tertiary_fixed: Color::hex("1C1D00").unwrap(),
                        tertiary_fixed_dim: Color::hex("CACA93").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("48491E").unwrap(),
                        surface_dim: Color::hex("19120D").unwrap(),
                        surface_bright: Color::hex("413731").unwrap(),
                        surface_container_lowest: Color::hex("140D08").unwrap(),
                        surface_container_low: Color::hex("221A15").unwrap(),
                        surface_container: Color::hex("261E19").unwrap(),
                        surface_container_high: Color::hex("312823").unwrap(),
                        surface_container_highest: Color::hex("3D332D").unwrap(),
                    },
                    medium_contrast: SchemeColors {
                        primary: Color::hex("FFBC92").unwrap(),
                        on_primary: Color::hex("290F00").unwrap(),
                        primary_container: Color::hex("C68051").unwrap(),
                        on_primary_container: Color::hex("000000").unwrap(),
                        secondary: Color::hex("E9C3AD").unwrap(),
                        on_secondary: Color::hex("251105").unwrap(),
                        secondary_container: Color::hex("AC8A75").unwrap(),
                        on_secondary_container: Color::hex("000000").unwrap(),
                        tertiary: Color::hex("CECE97").unwrap(),
                        on_tertiary: Color::hex("171700").unwrap(),
                        tertiary_container: Color::hex("939361").unwrap(),
                        on_tertiary_container: Color::hex("000000").unwrap(),
                        error: Color::hex("FFBAB1").unwrap(),
                        on_error: Color::hex("370001").unwrap(),
                        error_container: Color::hex("FF5449").unwrap(),
                        on_error_container: Color::hex("000000").unwrap(),
                        background: Color::hex("19120D").unwrap(),
                        on_background: Color::hex("F0DFD7").unwrap(),
                        surface: Color::hex("19120D").unwrap(),
                        on_surface: Color::hex("FFFAF8").unwrap(),
                        surface_variant: Color::hex("52443C").unwrap(),
                        on_surface_variant: Color::hex("DBC7BC").unwrap(),
                        outline: Color::hex("FFD200").unwrap(),
                        outline_variant: Color::hex("918076").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("F0DFD7").unwrap(),
                        inverse_on_surface: Color::hex("312823").unwrap(),
                        inverse_primary: Color::hex("703A10").unwrap(),
                        primary_fixed: Color::hex("FFDBC7").unwrap(),
                        on_primary_fixed: Color::hex("210B00").unwrap(),
                        primary_fixed_dim: Color::hex("FFB688").unwrap(),
                        on_primary_fixed_variant: Color::hex("592800").unwrap(),
                        secondary_fixed: Color::hex("FFDBC7").unwrap(),
                        on_secondary_fixed: Color::hex("1F0C02").unwrap(),
                        secondary_fixed_dim: Color::hex("E5BFA9").unwrap(),
                        on_secondary_fixed_variant: Color::hex("493121").unwrap(),
                        tertiary_fixed: Color::hex("E6E6AD").unwrap(),
                        on_tertiary_fixed: Color::hex("121200").unwrap(),
                        tertiary_fixed_dim: Color::hex("CACA93").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("37380F").unwrap(),
                        surface_dim: Color::hex("19120D").unwrap(),
                        surface_bright: Color::hex("413731").unwrap(),
                        surface_container_lowest: Color::hex("140D08").unwrap(),
                        surface_container_low: Color::hex("221A15").unwrap(),
                        surface_container: Color::hex("261E19").unwrap(),
                        surface_container_high: Color::hex("312823").unwrap(),
                        surface_container_highest: Color::hex("3D332D").unwrap(),
                    },
                    high_contrast: SchemeColors {
                        primary: Color::hex("FFFAF8").unwrap(),
                        on_primary: Color::hex("000000").unwrap(),
                        primary_container: Color::hex("FFBC92").unwrap(),
                        on_primary_container: Color::hex("000000").unwrap(),
                        secondary: Color::hex("FFFAF8").unwrap(),
                        on_secondary: Color::hex("000000").unwrap(),
                        secondary_container: Color::hex("E9C3AD").unwrap(),
                        on_secondary_container: Color::hex("000000").unwrap(),
                        tertiary: Color::hex("FFFEC5").unwrap(),
                        on_tertiary: Color::hex("000000").unwrap(),
                        tertiary_container: Color::hex("CECE97").unwrap(),
                        on_tertiary_container: Color::hex("000000").unwrap(),
                        error: Color::hex("FFF9F9").unwrap(),
                        on_error: Color::hex("000000").unwrap(),
                        error_container: Color::hex("FFBAB1").unwrap(),
                        on_error_container: Color::hex("000000").unwrap(),
                        background: Color::hex("19120D").unwrap(),
                        on_background: Color::hex("F0DFD7").unwrap(),
                        surface: Color::hex("19120D").unwrap(),
                        on_surface: Color::hex("FFFFFF").unwrap(),
                        surface_variant: Color::hex("52443C").unwrap(),
                        on_surface_variant: Color::hex("FFFAF8").unwrap(),
                        outline: Color::hex("FFD200").unwrap(),
                        outline_variant: Color::hex("DBC7BC").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("F0DFD7").unwrap(),
                        inverse_on_surface: Color::hex("000000").unwrap(),
                        inverse_primary: Color::hex("471F00").unwrap(),
                        primary_fixed: Color::hex("FFE1D0").unwrap(),
                        on_primary_fixed: Color::hex("000000").unwrap(),
                        primary_fixed_dim: Color::hex("FFBC92").unwrap(),
                        on_primary_fixed_variant: Color::hex("290F00").unwrap(),
                        secondary_fixed: Color::hex("FFE1D0").unwrap(),
                        on_secondary_fixed: Color::hex("000000").unwrap(),
                        secondary_fixed_dim: Color::hex("E9C3AD").unwrap(),
                        on_secondary_fixed_variant: Color::hex("251105").unwrap(),
                        tertiary_fixed: Color::hex("EBEAB1").unwrap(),
                        on_tertiary_fixed: Color::hex("000000").unwrap(),
                        tertiary_fixed_dim: Color::hex("CECE97").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("171700").unwrap(),
                        surface_dim: Color::hex("19120D").unwrap(),
                        surface_bright: Color::hex("413731").unwrap(),
                        surface_container_lowest: Color::hex("140D08").unwrap(),
                        surface_container_low: Color::hex("221A15").unwrap(),
                        surface_container: Color::hex("261E19").unwrap(),
                        surface_container_high: Color::hex("312823").unwrap(),
                        surface_container_highest: Color::hex("3D332D").unwrap(),
                    },
                },
            },
            palettes: ColorPalettes {
                primary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("1A0E07").unwrap(),
                    p_10: Color::hex("261911").unwrap(),
                    p_15: Color::hex("31231A").unwrap(),
                    p_20: Color::hex("3C2D24").unwrap(),
                    p_25: Color::hex("48382F").unwrap(),
                    p_30: Color::hex("54433A").unwrap(),
                    p_35: Color::hex("604F45").unwrap(),
                    p_40: Color::hex("6D5B50").unwrap(),
                    p_50: Color::hex("877368").unwrap(),
                    p_60: Color::hex("A28D81").unwrap(),
                    p_70: Color::hex("BDA79A").unwrap(),
                    p_80: Color::hex("DAC2B5").unwrap(),
                    p_90: Color::hex("F7DED0").unwrap(),
                    p_95: Color::hex("FFEDE4").unwrap(),
                    p_98: Color::hex("FFF8F5").unwrap(),
                    p_99: Color::hex("FFFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                secondary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("14100E").unwrap(),
                    p_10: Color::hex("1F1B18").unwrap(),
                    p_15: Color::hex("2A2522").unwrap(),
                    p_20: Color::hex("352F2C").unwrap(),
                    p_25: Color::hex("403A37").unwrap(),
                    p_30: Color::hex("4C4542").unwrap(),
                    p_35: Color::hex("58514E").unwrap(),
                    p_40: Color::hex("645D5A").unwrap(),
                    p_50: Color::hex("7D7672").unwrap(),
                    p_60: Color::hex("978F8B").unwrap(),
                    p_70: Color::hex("B2A9A5").unwrap(),
                    p_80: Color::hex("CEC5C0").unwrap(),
                    p_90: Color::hex("EBE0DC").unwrap(),
                    p_95: Color::hex("F9EFEA").unwrap(),
                    p_98: Color::hex("FFF8F5").unwrap(),
                    p_99: Color::hex("FFFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                tertiary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("11110B").unwrap(),
                    p_10: Color::hex("1C1C16").unwrap(),
                    p_15: Color::hex("26261F").unwrap(),
                    p_20: Color::hex("31312A").unwrap(),
                    p_25: Color::hex("3C3C34").unwrap(),
                    p_30: Color::hex("48473F").unwrap(),
                    p_35: Color::hex("54534B").unwrap(),
                    p_40: Color::hex("605F56").unwrap(),
                    p_50: Color::hex("79776F").unwrap(),
                    p_60: Color::hex("939188").unwrap(),
                    p_70: Color::hex("AEABA2").unwrap(),
                    p_80: Color::hex("C9C6BC").unwrap(),
                    p_90: Color::hex("E6E2D8").unwrap(),
                    p_95: Color::hex("F4F1E6").unwrap(),
                    p_98: Color::hex("FDF9EE").unwrap(),
                    p_99: Color::hex("FFFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                neutral: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("121110").unwrap(),
                    p_10: Color::hex("1D1B1B").unwrap(),
                    p_15: Color::hex("272525").unwrap(),
                    p_20: Color::hex("32302F").unwrap(),
                    p_25: Color::hex("3D3B3A").unwrap(),
                    p_30: Color::hex("494645").unwrap(),
                    p_35: Color::hex("545251").unwrap(),
                    p_40: Color::hex("615E5D").unwrap(),
                    p_50: Color::hex("7A7675").unwrap(),
                    p_60: Color::hex("94908F").unwrap(),
                    p_70: Color::hex("AFAAA9").unwrap(),
                    p_80: Color::hex("CAC5C4").unwrap(),
                    p_90: Color::hex("E7E1E0").unwrap(),
                    p_95: Color::hex("F5F0EE").unwrap(),
                    p_98: Color::hex("FEF8F6").unwrap(),
                    p_99: Color::hex("FFFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                neutral_variant: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("13100F").unwrap(),
                    p_10: Color::hex("1E1B1A").unwrap(),
                    p_15: Color::hex("282524").unwrap(),
                    p_20: Color::hex("33302E").unwrap(),
                    p_25: Color::hex("3E3B39").unwrap(),
                    p_30: Color::hex("4A4644").unwrap(),
                    p_35: Color::hex("555250").unwrap(),
                    p_40: Color::hex("625D5C").unwrap(),
                    p_50: Color::hex("7B7674").unwrap(),
                    p_60: Color::hex("95908D").unwrap(),
                    p_70: Color::hex("B0AAA8").unwrap(),
                    p_80: Color::hex("CBC5C3").unwrap(),
                    p_90: Color::hex("E8E1DE").unwrap(),
                    p_95: Color::hex("F6EFED").unwrap(),
                    p_98: Color::hex("FFF8F5").unwrap(),
                    p_99: Color::hex("FFFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
            },
        }
    }
}
