use bevy::prelude::*;

use super::theme_data::Contrast;

#[derive(Clone, Copy, Debug)]
pub enum Surface {
    Background,
    Surface,
    SurfaceVariant,
    SurfaceDim,
    SurfaceBright,
    InverseSurface,
}

#[derive(Clone, Copy, Debug)]
pub enum Accent {
    Primary,
    PrimaryFixed,
    PrimaryFixedDim,
    InversePrimary,
    Secondary,
    SecondaryFixed,
    SecondaryFixedDim,
    Tertiary,
    TertiaryFixed,
    TertiaryFixedDim,
    Error,
    Outline,
    OutlineVariant,
    Shadow,
    Scrim,
}

#[derive(Clone, Copy, Debug)]
pub enum Container {
    Primary,
    Secondary,
    Tertiary,
    Error,
    SurfaceLowest,
    SurfaceLow,
    SurfaceMid,
    SurfaceHigh,
    SurfaceHighest,
}

#[derive(Clone, Copy, Debug)]
pub enum On {
    Primary,
    PrimaryContainer,
    PrimaryFixed,
    PrimaryFixedVariant,
    Secondary,
    SecondaryContainer,
    SecondaryFixed,
    SecondaryFixedVariant,
    Tertiary,
    TertiaryContainer,
    TertiaryFixed,
    TertiaryFixedVariant,
    Error,
    ErrorContainer,
    Background,
    Surface,
    SurfaceVariant,
    InverseSurface,
}

#[derive(Clone, Debug, Default, Reflect)]
pub struct ExtendedColor {
    pub name: String,
    pub color: Color,
    pub description: String,
    pub harmonized: bool,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct CoreColors {
    pub primary: Color,
    pub secondary: Option<Color>,
    pub tertiary: Option<Color>,
    pub error: Option<Color>,
    pub neutral: Option<Color>,
    pub neutral_variant: Option<Color>,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct SchemeColors {
    pub primary: Color,
    pub on_primary: Color,
    pub primary_container: Color,
    pub on_primary_container: Color,
    pub secondary: Color,
    pub on_secondary: Color,
    pub secondary_container: Color,
    pub on_secondary_container: Color,
    pub tertiary: Color,
    pub on_tertiary: Color,
    pub tertiary_container: Color,
    pub on_tertiary_container: Color,
    pub error: Color,
    pub on_error: Color,
    pub error_container: Color,
    pub on_error_container: Color,
    pub background: Color,
    pub on_background: Color,
    pub surface: Color,
    pub on_surface: Color,
    pub surface_variant: Color,
    pub on_surface_variant: Color,
    pub outline: Color,
    pub outline_variant: Color,
    pub shadow: Color,
    pub scrim: Color,
    pub inverse_surface: Color,
    pub inverse_on_surface: Color,
    pub inverse_primary: Color,
    pub primary_fixed: Color,
    pub on_primary_fixed: Color,
    pub primary_fixed_dim: Color,
    pub on_primary_fixed_variant: Color,
    pub secondary_fixed: Color,
    pub on_secondary_fixed: Color,
    pub secondary_fixed_dim: Color,
    pub on_secondary_fixed_variant: Color,
    pub tertiary_fixed: Color,
    pub on_tertiary_fixed: Color,
    pub tertiary_fixed_dim: Color,
    pub on_tertiary_fixed_variant: Color,
    pub surface_dim: Color,
    pub surface_bright: Color,
    pub surface_container_lowest: Color,
    pub surface_container_low: Color,
    pub surface_container: Color,
    pub surface_container_high: Color,
    pub surface_container_highest: Color,
}

impl SchemeColors {
    pub fn surface(&self, surface: Surface) -> Color {
        match surface {
            Surface::Background => self.background,
            Surface::Surface => self.surface,
            Surface::InverseSurface => self.inverse_surface,
            Surface::SurfaceVariant => self.surface_variant,
            Surface::SurfaceDim => self.surface_dim,
            Surface::SurfaceBright => self.surface_bright,
        }
    }

    pub fn accent(&self, accent: Accent) -> Color {
        match accent {
            Accent::Primary => self.primary,
            Accent::PrimaryFixed => self.primary_fixed,
            Accent::PrimaryFixedDim => self.primary_fixed_dim,
            Accent::InversePrimary => self.inverse_primary,
            Accent::Secondary => self.secondary,
            Accent::SecondaryFixed => self.secondary_fixed,
            Accent::SecondaryFixedDim => self.secondary_fixed_dim,
            Accent::Tertiary => self.tertiary,
            Accent::TertiaryFixed => self.tertiary_fixed,
            Accent::TertiaryFixedDim => self.tertiary_fixed_dim,
            Accent::Error => self.error,
            Accent::Outline => self.outline,
            Accent::OutlineVariant => self.outline_variant,
            Accent::Shadow => self.shadow,
            Accent::Scrim => self.scrim,
        }
    }

    pub fn container(&self, container: Container) -> Color {
        match container {
            Container::Primary => self.primary_container,
            Container::Secondary => self.secondary_container,
            Container::Tertiary => self.tertiary_container,
            Container::Error => self.error_container,
            Container::SurfaceLowest => self.surface_container_lowest,
            Container::SurfaceLow => self.surface_container_low,
            Container::SurfaceMid => self.surface_container,
            Container::SurfaceHigh => self.surface_container_high,
            Container::SurfaceHighest => self.surface_container_highest,
        }
    }

    pub fn on(&self, on: On) -> Color {
        match on {
            On::Primary => self.on_primary,
            On::PrimaryContainer => self.on_primary_container,
            On::PrimaryFixed => self.on_primary_fixed,
            On::PrimaryFixedVariant => self.on_primary_fixed_variant,
            On::Secondary => self.on_secondary,
            On::SecondaryContainer => self.on_secondary_container,
            On::SecondaryFixed => self.on_secondary_fixed,
            On::SecondaryFixedVariant => self.on_secondary_fixed_variant,
            On::Tertiary => self.on_tertiary,
            On::TertiaryContainer => self.on_tertiary_container,
            On::TertiaryFixed => self.on_tertiary_fixed,
            On::TertiaryFixedVariant => self.on_tertiary_fixed_variant,
            On::Error => self.on_error,
            On::ErrorContainer => self.on_error_container,
            On::Background => self.on_background,
            On::Surface => self.on_surface,
            On::SurfaceVariant => self.on_surface_variant,
            On::InverseSurface => self.inverse_on_surface,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorScheme {
    pub colors: SchemeColors,
    pub medium_contrast: SchemeColors,
    pub high_contrast: SchemeColors,
}

impl ColorScheme {
    pub fn contrast(&self, contrast: Contrast) -> SchemeColors {
        match contrast {
            Contrast::Standard => self.colors,
            Contrast::Medium => self.medium_contrast,
            Contrast::High => self.high_contrast,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorSchemes {
    pub light: ColorScheme,
    pub dark: ColorScheme,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorPalette {
    pub p_0: Color,
    pub p_5: Color,
    pub p_10: Color,
    pub p_15: Color,
    pub p_20: Color,
    pub p_25: Color,
    pub p_30: Color,
    pub p_35: Color,
    pub p_40: Color,
    pub p_50: Color,
    pub p_60: Color,
    pub p_70: Color,
    pub p_80: Color,
    pub p_90: Color,
    pub p_95: Color,
    pub p_98: Color,
    pub p_99: Color,
    pub p_100: Color,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorPalettes {
    pub primary: ColorPalette,
    pub secondary: ColorPalette,
    pub tertiary: ColorPalette,
    pub neutral: ColorPalette,
    pub neutral_variant: ColorPalette,
}

// TODO: write asset loader for theme colors and load it from a material-theme.json
/// Loosly Follows Material3 theme format
#[derive(Clone, Debug, Reflect)]
pub struct ThemeColors {
    pub description: String,
    // TODO: Generate colors from seed & core colors?
    pub seed: Color,
    pub core_colors: CoreColors,
    pub extended_colors: Vec<ExtendedColor>,
    pub schemes: ColorSchemes,
    pub palettes: ColorPalettes,
}

impl Default for ThemeColors {
    fn default() -> Self {
        Self {
            description: "Sickle UI Theme".into(),
            seed: Color::hex("037E90").unwrap(),
            core_colors: CoreColors {
                primary: Color::hex("037E90").unwrap(),
                ..default()
            },
            extended_colors: Default::default(),
            schemes: ColorSchemes {
                light: ColorScheme {
                    colors: SchemeColors {
                        primary: Color::hex("006877").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("A4EEFF").unwrap(),
                        on_primary_container: Color::hex("001F25").unwrap(),
                        secondary: Color::hex("4B6268").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("CDE7EE").unwrap(),
                        on_secondary_container: Color::hex("051F24").unwrap(),
                        tertiary: Color::hex("555D7E").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("DCE1FF").unwrap(),
                        on_tertiary_container: Color::hex("111A37").unwrap(),
                        error: Color::hex("BA1A1A").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("FFDAD6").unwrap(),
                        on_error_container: Color::hex("410002").unwrap(),
                        background: Color::hex("F5FAFC").unwrap(),
                        on_background: Color::hex("171D1E").unwrap(),
                        surface: Color::hex("F5FAFC").unwrap(),
                        on_surface: Color::hex("171D1E").unwrap(),
                        surface_variant: Color::hex("DBE4E7").unwrap(),
                        on_surface_variant: Color::hex("3F484B").unwrap(),
                        outline: Color::hex("6F797B").unwrap(),
                        outline_variant: Color::hex("BFC8CB").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("2B3133").unwrap(),
                        inverse_on_surface: Color::hex("ECF2F3").unwrap(),
                        inverse_primary: Color::hex("83D2E4").unwrap(),
                        primary_fixed: Color::hex("A4EEFF").unwrap(),
                        on_primary_fixed: Color::hex("001F25").unwrap(),
                        primary_fixed_dim: Color::hex("83D2E4").unwrap(),
                        on_primary_fixed_variant: Color::hex("004E5A").unwrap(),
                        secondary_fixed: Color::hex("CDE7EE").unwrap(),
                        on_secondary_fixed: Color::hex("051F24").unwrap(),
                        secondary_fixed_dim: Color::hex("B2CBD1").unwrap(),
                        on_secondary_fixed_variant: Color::hex("334A50").unwrap(),
                        tertiary_fixed: Color::hex("DCE1FF").unwrap(),
                        on_tertiary_fixed: Color::hex("111A37").unwrap(),
                        tertiary_fixed_dim: Color::hex("BDC5EB").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("3D4565").unwrap(),
                        surface_dim: Color::hex("D5DBDD").unwrap(),
                        surface_bright: Color::hex("F5FAFC").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("EFF4F6").unwrap(),
                        surface_container: Color::hex("E9EFF0").unwrap(),
                        surface_container_high: Color::hex("E4E9EB").unwrap(),
                        surface_container_highest: Color::hex("DEE3E5").unwrap(),
                    },
                    medium_contrast: SchemeColors {
                        primary: Color::hex("004A55").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("277F8F").unwrap(),
                        on_primary_container: Color::hex("FFFFFF").unwrap(),
                        secondary: Color::hex("2F464C").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("61797E").unwrap(),
                        on_secondary_container: Color::hex("FFFFFF").unwrap(),
                        tertiary: Color::hex("394161").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("6B7395").unwrap(),
                        on_tertiary_container: Color::hex("FFFFFF").unwrap(),
                        error: Color::hex("8C0009").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("DA342E").unwrap(),
                        on_error_container: Color::hex("FFFFFF").unwrap(),
                        background: Color::hex("F5FAFC").unwrap(),
                        on_background: Color::hex("171D1E").unwrap(),
                        surface: Color::hex("F5FAFC").unwrap(),
                        on_surface: Color::hex("171D1E").unwrap(),
                        surface_variant: Color::hex("DBE4E7").unwrap(),
                        on_surface_variant: Color::hex("3B4447").unwrap(),
                        outline: Color::hex("576163").unwrap(),
                        outline_variant: Color::hex("737C7F").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("2B3133").unwrap(),
                        inverse_on_surface: Color::hex("ECF2F3").unwrap(),
                        inverse_primary: Color::hex("83D2E4").unwrap(),
                        primary_fixed: Color::hex("277F8F").unwrap(),
                        on_primary_fixed: Color::hex("FFFFFF").unwrap(),
                        primary_fixed_dim: Color::hex("006574").unwrap(),
                        on_primary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed: Color::hex("61797E").unwrap(),
                        on_secondary_fixed: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed_dim: Color::hex("486065").unwrap(),
                        on_secondary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed: Color::hex("6B7395").unwrap(),
                        on_tertiary_fixed: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed_dim: Color::hex("525B7B").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        surface_dim: Color::hex("D5DBDD").unwrap(),
                        surface_bright: Color::hex("F5FAFC").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("EFF4F6").unwrap(),
                        surface_container: Color::hex("E9EFF0").unwrap(),
                        surface_container_high: Color::hex("E4E9EB").unwrap(),
                        surface_container_highest: Color::hex("DEE3E5").unwrap(),
                    },
                    high_contrast: SchemeColors {
                        primary: Color::hex("00262D").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("004A55").unwrap(),
                        on_primary_container: Color::hex("FFFFFF").unwrap(),
                        secondary: Color::hex("0D252B").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("2F464C").unwrap(),
                        on_secondary_container: Color::hex("FFFFFF").unwrap(),
                        tertiary: Color::hex("18213E").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("394161").unwrap(),
                        on_tertiary_container: Color::hex("FFFFFF").unwrap(),
                        error: Color::hex("4E0002").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("8C0009").unwrap(),
                        on_error_container: Color::hex("FFFFFF").unwrap(),
                        background: Color::hex("F5FAFC").unwrap(),
                        on_background: Color::hex("171D1E").unwrap(),
                        surface: Color::hex("F5FAFC").unwrap(),
                        on_surface: Color::hex("000000").unwrap(),
                        surface_variant: Color::hex("DBE4E7").unwrap(),
                        on_surface_variant: Color::hex("1D2527").unwrap(),
                        outline: Color::hex("3B4447").unwrap(),
                        outline_variant: Color::hex("3B4447").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("2B3133").unwrap(),
                        inverse_on_surface: Color::hex("FFFFFF").unwrap(),
                        inverse_primary: Color::hex("C6F4FF").unwrap(),
                        primary_fixed: Color::hex("004A55").unwrap(),
                        on_primary_fixed: Color::hex("FFFFFF").unwrap(),
                        primary_fixed_dim: Color::hex("00323A").unwrap(),
                        on_primary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed: Color::hex("2F464C").unwrap(),
                        on_secondary_fixed: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed_dim: Color::hex("183035").unwrap(),
                        on_secondary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed: Color::hex("394161").unwrap(),
                        on_tertiary_fixed: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed_dim: Color::hex("232B49").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        surface_dim: Color::hex("D5DBDD").unwrap(),
                        surface_bright: Color::hex("F5FAFC").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("EFF4F6").unwrap(),
                        surface_container: Color::hex("E9EFF0").unwrap(),
                        surface_container_high: Color::hex("E4E9EB").unwrap(),
                        surface_container_highest: Color::hex("DEE3E5").unwrap(),
                    },
                },
                dark: ColorScheme {
                    colors: SchemeColors {
                        primary: Color::hex("83D2E4").unwrap(),
                        on_primary: Color::hex("00363F").unwrap(),
                        primary_container: Color::hex("004E5A").unwrap(),
                        on_primary_container: Color::hex("A4EEFF").unwrap(),
                        secondary: Color::hex("B2CBD1").unwrap(),
                        on_secondary: Color::hex("1C3439").unwrap(),
                        secondary_container: Color::hex("334A50").unwrap(),
                        on_secondary_container: Color::hex("CDE7EE").unwrap(),
                        tertiary: Color::hex("BDC5EB").unwrap(),
                        on_tertiary: Color::hex("262F4D").unwrap(),
                        tertiary_container: Color::hex("3D4565").unwrap(),
                        on_tertiary_container: Color::hex("DCE1FF").unwrap(),
                        error: Color::hex("FFB4AB").unwrap(),
                        on_error: Color::hex("690005").unwrap(),
                        error_container: Color::hex("93000A").unwrap(),
                        on_error_container: Color::hex("FFDAD6").unwrap(),
                        background: Color::hex("0E1416").unwrap(),
                        on_background: Color::hex("DEE3E5").unwrap(),
                        surface: Color::hex("0E1416").unwrap(),
                        on_surface: Color::hex("DEE3E5").unwrap(),
                        surface_variant: Color::hex("3F484B").unwrap(),
                        on_surface_variant: Color::hex("BFC8CB").unwrap(),
                        outline: Color::hex("899295").unwrap(),
                        outline_variant: Color::hex("3F484B").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("DEE3E5").unwrap(),
                        inverse_on_surface: Color::hex("2B3133").unwrap(),
                        inverse_primary: Color::hex("006877").unwrap(),
                        primary_fixed: Color::hex("A4EEFF").unwrap(),
                        on_primary_fixed: Color::hex("001F25").unwrap(),
                        primary_fixed_dim: Color::hex("83D2E4").unwrap(),
                        on_primary_fixed_variant: Color::hex("004E5A").unwrap(),
                        secondary_fixed: Color::hex("CDE7EE").unwrap(),
                        on_secondary_fixed: Color::hex("051F24").unwrap(),
                        secondary_fixed_dim: Color::hex("B2CBD1").unwrap(),
                        on_secondary_fixed_variant: Color::hex("334A50").unwrap(),
                        tertiary_fixed: Color::hex("DCE1FF").unwrap(),
                        on_tertiary_fixed: Color::hex("111A37").unwrap(),
                        tertiary_fixed_dim: Color::hex("BDC5EB").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("3D4565").unwrap(),
                        surface_dim: Color::hex("0E1416").unwrap(),
                        surface_bright: Color::hex("343A3C").unwrap(),
                        surface_container_lowest: Color::hex("090F11").unwrap(),
                        surface_container_low: Color::hex("171D1E").unwrap(),
                        surface_container: Color::hex("1B2122").unwrap(),
                        surface_container_high: Color::hex("252B2C").unwrap(),
                        surface_container_highest: Color::hex("303637").unwrap(),
                    },
                    medium_contrast: SchemeColors {
                        primary: Color::hex("87D7E8").unwrap(),
                        on_primary: Color::hex("00191F").unwrap(),
                        primary_container: Color::hex("4A9CAC").unwrap(),
                        on_primary_container: Color::hex("000000").unwrap(),
                        secondary: Color::hex("B6CFD6").unwrap(),
                        on_secondary: Color::hex("01191E").unwrap(),
                        secondary_container: Color::hex("7C959B").unwrap(),
                        on_secondary_container: Color::hex("000000").unwrap(),
                        tertiary: Color::hex("C1C9EF").unwrap(),
                        on_tertiary: Color::hex("0B1431").unwrap(),
                        tertiary_container: Color::hex("878FB3").unwrap(),
                        on_tertiary_container: Color::hex("000000").unwrap(),
                        error: Color::hex("FFBAB1").unwrap(),
                        on_error: Color::hex("370001").unwrap(),
                        error_container: Color::hex("FF5449").unwrap(),
                        on_error_container: Color::hex("000000").unwrap(),
                        background: Color::hex("0E1416").unwrap(),
                        on_background: Color::hex("DEE3E5").unwrap(),
                        surface: Color::hex("0E1416").unwrap(),
                        on_surface: Color::hex("F6FCFD").unwrap(),
                        surface_variant: Color::hex("3F484B").unwrap(),
                        on_surface_variant: Color::hex("C3CCCF").unwrap(),
                        outline: Color::hex("9BA4A7").unwrap(),
                        outline_variant: Color::hex("7B8587").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("DEE3E5").unwrap(),
                        inverse_on_surface: Color::hex("252B2D").unwrap(),
                        inverse_primary: Color::hex("00505C").unwrap(),
                        primary_fixed: Color::hex("A4EEFF").unwrap(),
                        on_primary_fixed: Color::hex("001418").unwrap(),
                        primary_fixed_dim: Color::hex("83D2E4").unwrap(),
                        on_primary_fixed_variant: Color::hex("003C46").unwrap(),
                        secondary_fixed: Color::hex("CDE7EE").unwrap(),
                        on_secondary_fixed: Color::hex("001418").unwrap(),
                        secondary_fixed_dim: Color::hex("B2CBD1").unwrap(),
                        on_secondary_fixed_variant: Color::hex("223A3F").unwrap(),
                        tertiary_fixed: Color::hex("DCE1FF").unwrap(),
                        on_tertiary_fixed: Color::hex("060F2C").unwrap(),
                        tertiary_fixed_dim: Color::hex("BDC5EB").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("2C3553").unwrap(),
                        surface_dim: Color::hex("0E1416").unwrap(),
                        surface_bright: Color::hex("343A3C").unwrap(),
                        surface_container_lowest: Color::hex("090F11").unwrap(),
                        surface_container_low: Color::hex("171D1E").unwrap(),
                        surface_container: Color::hex("1B2122").unwrap(),
                        surface_container_high: Color::hex("252B2C").unwrap(),
                        surface_container_highest: Color::hex("303637").unwrap(),
                    },
                    high_contrast: SchemeColors {
                        primary: Color::hex("F3FCFF").unwrap(),
                        on_primary: Color::hex("000000").unwrap(),
                        primary_container: Color::hex("87D7E8").unwrap(),
                        on_primary_container: Color::hex("000000").unwrap(),
                        secondary: Color::hex("F3FCFF").unwrap(),
                        on_secondary: Color::hex("000000").unwrap(),
                        secondary_container: Color::hex("B6CFD6").unwrap(),
                        on_secondary_container: Color::hex("000000").unwrap(),
                        tertiary: Color::hex("FCFAFF").unwrap(),
                        on_tertiary: Color::hex("000000").unwrap(),
                        tertiary_container: Color::hex("C1C9EF").unwrap(),
                        on_tertiary_container: Color::hex("000000").unwrap(),
                        error: Color::hex("FFF9F9").unwrap(),
                        on_error: Color::hex("000000").unwrap(),
                        error_container: Color::hex("FFBAB1").unwrap(),
                        on_error_container: Color::hex("000000").unwrap(),
                        background: Color::hex("0E1416").unwrap(),
                        on_background: Color::hex("DEE3E5").unwrap(),
                        surface: Color::hex("0E1416").unwrap(),
                        on_surface: Color::hex("FFFFFF").unwrap(),
                        surface_variant: Color::hex("3F484B").unwrap(),
                        on_surface_variant: Color::hex("F3FCFF").unwrap(),
                        outline: Color::hex("C3CCCF").unwrap(),
                        outline_variant: Color::hex("C3CCCF").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("DEE3E5").unwrap(),
                        inverse_on_surface: Color::hex("000000").unwrap(),
                        inverse_primary: Color::hex("002F37").unwrap(),
                        primary_fixed: Color::hex("B4F1FF").unwrap(),
                        on_primary_fixed: Color::hex("000000").unwrap(),
                        primary_fixed_dim: Color::hex("87D7E8").unwrap(),
                        on_primary_fixed_variant: Color::hex("00191F").unwrap(),
                        secondary_fixed: Color::hex("D2EBF2").unwrap(),
                        on_secondary_fixed: Color::hex("000000").unwrap(),
                        secondary_fixed_dim: Color::hex("B6CFD6").unwrap(),
                        on_secondary_fixed_variant: Color::hex("01191E").unwrap(),
                        tertiary_fixed: Color::hex("E2E6FF").unwrap(),
                        on_tertiary_fixed: Color::hex("000000").unwrap(),
                        tertiary_fixed_dim: Color::hex("C1C9EF").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("0B1431").unwrap(),
                        surface_dim: Color::hex("0E1416").unwrap(),
                        surface_bright: Color::hex("343A3C").unwrap(),
                        surface_container_lowest: Color::hex("090F11").unwrap(),
                        surface_container_low: Color::hex("171D1E").unwrap(),
                        surface_container: Color::hex("1B2122").unwrap(),
                        surface_container_high: Color::hex("252B2C").unwrap(),
                        surface_container_highest: Color::hex("303637").unwrap(),
                    },
                },
            },
            palettes: ColorPalettes {
                primary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("001418").unwrap(),
                    p_10: Color::hex("001F25").unwrap(),
                    p_15: Color::hex("002A32").unwrap(),
                    p_20: Color::hex("00363F").unwrap(),
                    p_25: Color::hex("00424C").unwrap(),
                    p_30: Color::hex("004E5A").unwrap(),
                    p_35: Color::hex("005B69").unwrap(),
                    p_40: Color::hex("006877").unwrap(),
                    p_50: Color::hex("128395").unwrap(),
                    p_60: Color::hex("3C9DAF").unwrap(),
                    p_70: Color::hex("5BB8CB").unwrap(),
                    p_80: Color::hex("78D4E7").unwrap(),
                    p_90: Color::hex("A4EEFF").unwrap(),
                    p_95: Color::hex("D5F7FF").unwrap(),
                    p_98: Color::hex("EFFCFF").unwrap(),
                    p_99: Color::hex("F7FDFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                secondary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("021317").unwrap(),
                    p_10: Color::hex("0C1E22").unwrap(),
                    p_15: Color::hex("17282C").unwrap(),
                    p_20: Color::hex("223337").unwrap(),
                    p_25: Color::hex("2D3E42").unwrap(),
                    p_30: Color::hex("384A4E").unwrap(),
                    p_35: Color::hex("44555A").unwrap(),
                    p_40: Color::hex("4F6166").unwrap(),
                    p_50: Color::hex("687A7F").unwrap(),
                    p_60: Color::hex("819499").unwrap(),
                    p_70: Color::hex("9CAEB3").unwrap(),
                    p_80: Color::hex("B7CACF").unwrap(),
                    p_90: Color::hex("D2E6EB").unwrap(),
                    p_95: Color::hex("E1F4F9").unwrap(),
                    p_98: Color::hex("EFFCFF").unwrap(),
                    p_99: Color::hex("F7FDFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                tertiary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("091025").unwrap(),
                    p_10: Color::hex("141A31").unwrap(),
                    p_15: Color::hex("1E253B").unwrap(),
                    p_20: Color::hex("292F47").unwrap(),
                    p_25: Color::hex("343A52").unwrap(),
                    p_30: Color::hex("40465E").unwrap(),
                    p_35: Color::hex("4B516A").unwrap(),
                    p_40: Color::hex("575D77").unwrap(),
                    p_50: Color::hex("707691").unwrap(),
                    p_60: Color::hex("8A90AB").unwrap(),
                    p_70: Color::hex("A4AAC7").unwrap(),
                    p_80: Color::hex("BFC5E3").unwrap(),
                    p_90: Color::hex("DCE1FF").unwrap(),
                    p_95: Color::hex("EFF0FF").unwrap(),
                    p_98: Color::hex("FAF8FF").unwrap(),
                    p_99: Color::hex("FEFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                neutral: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("0F1112").unwrap(),
                    p_10: Color::hex("191C1D").unwrap(),
                    p_15: Color::hex("242627").unwrap(),
                    p_20: Color::hex("2E3131").unwrap(),
                    p_25: Color::hex("393C3C").unwrap(),
                    p_30: Color::hex("454748").unwrap(),
                    p_35: Color::hex("505353").unwrap(),
                    p_40: Color::hex("5D5F5F").unwrap(),
                    p_50: Color::hex("757778").unwrap(),
                    p_60: Color::hex("8F9191").unwrap(),
                    p_70: Color::hex("AAABAC").unwrap(),
                    p_80: Color::hex("C5C7C7").unwrap(),
                    p_90: Color::hex("E2E2E3").unwrap(),
                    p_95: Color::hex("F0F1F1").unwrap(),
                    p_98: Color::hex("F9F9FA").unwrap(),
                    p_99: Color::hex("FCFCFD").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                neutral_variant: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("0B1214").unwrap(),
                    p_10: Color::hex("161D1E").unwrap(),
                    p_15: Color::hex("202729").unwrap(),
                    p_20: Color::hex("2B3233").unwrap(),
                    p_25: Color::hex("363D3E").unwrap(),
                    p_30: Color::hex("41484A").unwrap(),
                    p_35: Color::hex("4D5455").unwrap(),
                    p_40: Color::hex("596061").unwrap(),
                    p_50: Color::hex("71787A").unwrap(),
                    p_60: Color::hex("8B9294").unwrap(),
                    p_70: Color::hex("A6ACAE").unwrap(),
                    p_80: Color::hex("C1C8CA").unwrap(),
                    p_90: Color::hex("DDE4E5").unwrap(),
                    p_95: Color::hex("EBF2F4").unwrap(),
                    p_98: Color::hex("F4FAFC").unwrap(),
                    p_99: Color::hex("F7FDFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
            },
        }
    }
}
