use bevy::prelude::*;

use super::theme_data::Contrast;

#[derive(Clone, Copy, Debug)]
pub enum Surface {
    Background,
    Surface,
    SurfaceVariant,
    SurfaceDim,
    SurfaceBright,
    InverseSurface,
}

#[derive(Clone, Copy, Debug)]
pub enum Accent {
    Primary,
    PrimaryFixed,
    PrimaryFixedDim,
    InversePrimary,
    Secondary,
    SecondaryFixed,
    SecondaryFixedDim,
    Tertiary,
    TertiaryFixed,
    TertiaryFixedDim,
    Error,
    Outline,
    OutlineVariant,
    Shadow,
    Scrim,
}

#[derive(Clone, Copy, Debug)]
pub enum Container {
    Primary,
    Secondary,
    Tertiary,
    Error,
    SurfaceLowest,
    SurfaceLow,
    SurfaceMid,
    SurfaceHigh,
    SurfaceHighest,
}

#[derive(Clone, Copy, Debug)]
pub enum On {
    Primary,
    PrimaryContainer,
    PrimaryFixed,
    PrimaryFixedVariant,
    Secondary,
    SecondaryContainer,
    SecondaryFixed,
    SecondaryFixedVariant,
    Tertiary,
    TertiaryContainer,
    TertiaryFixed,
    TertiaryFixedVariant,
    Error,
    ErrorContainer,
    Background,
    Surface,
    SurfaceVariant,
    InverseSurface,
}

#[derive(Clone, Debug, Default, Reflect)]
pub struct ExtendedColor {
    pub name: String,
    pub color: Color,
    pub description: String,
    pub harmonized: bool,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct CoreColors {
    pub primary: Color,
    pub secondary: Option<Color>,
    pub tertiary: Option<Color>,
    pub error: Option<Color>,
    pub neutral: Option<Color>,
    pub neutral_variant: Option<Color>,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct SchemeColors {
    pub primary: Color,
    pub on_primary: Color,
    pub primary_container: Color,
    pub on_primary_container: Color,
    pub secondary: Color,
    pub on_secondary: Color,
    pub secondary_container: Color,
    pub on_secondary_container: Color,
    pub tertiary: Color,
    pub on_tertiary: Color,
    pub tertiary_container: Color,
    pub on_tertiary_container: Color,
    pub error: Color,
    pub on_error: Color,
    pub error_container: Color,
    pub on_error_container: Color,
    pub background: Color,
    pub on_background: Color,
    pub surface: Color,
    pub on_surface: Color,
    pub surface_variant: Color,
    pub on_surface_variant: Color,
    pub outline: Color,
    pub outline_variant: Color,
    pub shadow: Color,
    pub scrim: Color,
    pub inverse_surface: Color,
    pub inverse_on_surface: Color,
    pub inverse_primary: Color,
    pub primary_fixed: Color,
    pub on_primary_fixed: Color,
    pub primary_fixed_dim: Color,
    pub on_primary_fixed_variant: Color,
    pub secondary_fixed: Color,
    pub on_secondary_fixed: Color,
    pub secondary_fixed_dim: Color,
    pub on_secondary_fixed_variant: Color,
    pub tertiary_fixed: Color,
    pub on_tertiary_fixed: Color,
    pub tertiary_fixed_dim: Color,
    pub on_tertiary_fixed_variant: Color,
    pub surface_dim: Color,
    pub surface_bright: Color,
    pub surface_container_lowest: Color,
    pub surface_container_low: Color,
    pub surface_container: Color,
    pub surface_container_high: Color,
    pub surface_container_highest: Color,
}

impl SchemeColors {
    pub fn surface(&self, surface: Surface) -> Color {
        match surface {
            Surface::Background => self.background,
            Surface::Surface => self.surface,
            Surface::InverseSurface => self.inverse_surface,
            Surface::SurfaceVariant => self.surface_variant,
            Surface::SurfaceDim => self.surface_dim,
            Surface::SurfaceBright => self.surface_bright,
        }
    }

    pub fn accent(&self, accent: Accent) -> Color {
        match accent {
            Accent::Primary => self.primary,
            Accent::PrimaryFixed => self.primary_fixed,
            Accent::PrimaryFixedDim => self.primary_fixed_dim,
            Accent::InversePrimary => self.inverse_primary,
            Accent::Secondary => self.secondary,
            Accent::SecondaryFixed => self.secondary_fixed,
            Accent::SecondaryFixedDim => self.secondary_fixed_dim,
            Accent::Tertiary => self.tertiary,
            Accent::TertiaryFixed => self.tertiary_fixed,
            Accent::TertiaryFixedDim => self.tertiary_fixed_dim,
            Accent::Error => self.error,
            Accent::Outline => self.outline,
            Accent::OutlineVariant => self.outline_variant,
            Accent::Shadow => self.shadow,
            Accent::Scrim => self.scrim,
        }
    }

    pub fn container(&self, container: Container) -> Color {
        match container {
            Container::Primary => self.primary_container,
            Container::Secondary => self.secondary_container,
            Container::Tertiary => self.tertiary_container,
            Container::Error => self.error_container,
            Container::SurfaceLowest => self.surface_container_lowest,
            Container::SurfaceLow => self.surface_container_low,
            Container::SurfaceMid => self.surface_container,
            Container::SurfaceHigh => self.surface_container_high,
            Container::SurfaceHighest => self.surface_container_highest,
        }
    }

    pub fn on(&self, on: On) -> Color {
        match on {
            On::Primary => self.on_primary,
            On::PrimaryContainer => self.on_primary_container,
            On::PrimaryFixed => self.on_primary_fixed,
            On::PrimaryFixedVariant => self.on_primary_fixed_variant,
            On::Secondary => self.on_secondary,
            On::SecondaryContainer => self.on_secondary_container,
            On::SecondaryFixed => self.on_secondary_fixed,
            On::SecondaryFixedVariant => self.on_secondary_fixed_variant,
            On::Tertiary => self.on_tertiary,
            On::TertiaryContainer => self.on_tertiary_container,
            On::TertiaryFixed => self.on_tertiary_fixed,
            On::TertiaryFixedVariant => self.on_tertiary_fixed_variant,
            On::Error => self.on_error,
            On::ErrorContainer => self.on_error_container,
            On::Background => self.on_background,
            On::Surface => self.on_surface,
            On::SurfaceVariant => self.on_surface_variant,
            On::InverseSurface => self.inverse_on_surface,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorScheme {
    pub colors: SchemeColors,
    pub medium_contrast: SchemeColors,
    pub high_contrast: SchemeColors,
}

impl ColorScheme {
    pub fn contrast(&self, contrast: Contrast) -> SchemeColors {
        match contrast {
            Contrast::Standard => self.colors,
            Contrast::Medium => self.medium_contrast,
            Contrast::High => self.high_contrast,
        }
    }
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorSchemes {
    pub light: ColorScheme,
    pub dark: ColorScheme,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorPalette {
    pub p_0: Color,
    pub p_5: Color,
    pub p_10: Color,
    pub p_15: Color,
    pub p_20: Color,
    pub p_25: Color,
    pub p_30: Color,
    pub p_35: Color,
    pub p_40: Color,
    pub p_50: Color,
    pub p_60: Color,
    pub p_70: Color,
    pub p_80: Color,
    pub p_90: Color,
    pub p_95: Color,
    pub p_98: Color,
    pub p_99: Color,
    pub p_100: Color,
}

#[derive(Clone, Copy, Debug, Default, Reflect)]
pub struct ColorPalettes {
    pub primary: ColorPalette,
    pub secondary: ColorPalette,
    pub tertiary: ColorPalette,
    pub neutral: ColorPalette,
    pub neutral_variant: ColorPalette,
}

// TODO: write asset loader for theme colors and load it from a material-theme.json
/// Loosly Follows Material3 theme format
#[derive(Clone, Debug, Reflect)]
pub struct ThemeColors {
    pub description: String,
    // TODO: Generate colors from seed & core colors?
    pub seed: Color,
    pub core_colors: CoreColors,
    pub extended_colors: Vec<ExtendedColor>,
    pub schemes: ColorSchemes,
    pub palettes: ColorPalettes,
}

impl Default for ThemeColors {
    fn default() -> Self {
        Self {
            description: "Sickle UI Theme".into(),
            seed: Color::hex("FAEB8A").unwrap(),
            core_colors: CoreColors {
                primary: Color::hex("FAEB8A").unwrap(),
                secondary: Color::hex("1A1A1A").unwrap().into(),
                neutral: Color::hex("262829").unwrap().into(),
                ..default()
            },
            extended_colors: Default::default(),
            schemes: ColorSchemes {
                light: ColorScheme {
                    colors: SchemeColors {
                        primary: Color::hex("695F12").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("F2E48A").unwrap(),
                        on_primary_container: Color::hex("201C00").unwrap(),
                        secondary: Color::hex("006874").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("9EEFFD").unwrap(),
                        on_secondary_container: Color::hex("001F24").unwrap(),
                        tertiary: Color::hex("416652").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("C3ECD2").unwrap(),
                        on_tertiary_container: Color::hex("002113").unwrap(),
                        error: Color::hex("BA1A1A").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("FFDAD6").unwrap(),
                        on_error_container: Color::hex("410002").unwrap(),
                        background: Color::hex("FFF9EB").unwrap(),
                        on_background: Color::hex("1D1C13").unwrap(),
                        surface: Color::hex("FFF9EB").unwrap(),
                        on_surface: Color::hex("1D1C13").unwrap(),
                        surface_variant: Color::hex("E8E2D0").unwrap(),
                        on_surface_variant: Color::hex("4A4739").unwrap(),
                        outline: Color::hex("7B7768").unwrap(),
                        outline_variant: Color::hex("CCC6B5").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("323027").unwrap(),
                        inverse_on_surface: Color::hex("F6F0E3").unwrap(),
                        inverse_primary: Color::hex("D5C871").unwrap(),
                        primary_fixed: Color::hex("F2E48A").unwrap(),
                        on_primary_fixed: Color::hex("201C00").unwrap(),
                        primary_fixed_dim: Color::hex("D5C871").unwrap(),
                        on_primary_fixed_variant: Color::hex("504700").unwrap(),
                        secondary_fixed: Color::hex("9EEFFD").unwrap(),
                        on_secondary_fixed: Color::hex("001F24").unwrap(),
                        secondary_fixed_dim: Color::hex("82D3E0").unwrap(),
                        on_secondary_fixed_variant: Color::hex("004F58").unwrap(),
                        tertiary_fixed: Color::hex("C3ECD2").unwrap(),
                        on_tertiary_fixed: Color::hex("002113").unwrap(),
                        tertiary_fixed_dim: Color::hex("A7D0B7").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("294E3B").unwrap(),
                        surface_dim: Color::hex("DFDACC").unwrap(),
                        surface_bright: Color::hex("FFF9EB").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("F9F3E5").unwrap(),
                        surface_container: Color::hex("F3EDE0").unwrap(),
                        surface_container_high: Color::hex("EDE8DA").unwrap(),
                        surface_container_highest: Color::hex("E7E2D5").unwrap(),
                    },
                    medium_contrast: SchemeColors {
                        primary: Color::hex("4B4300").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("807628").unwrap(),
                        on_primary_container: Color::hex("FFFFFF").unwrap(),
                        secondary: Color::hex("004A53").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("25808C").unwrap(),
                        on_secondary_container: Color::hex("FFFFFF").unwrap(),
                        tertiary: Color::hex("254A37").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("577D67").unwrap(),
                        on_tertiary_container: Color::hex("FFFFFF").unwrap(),
                        error: Color::hex("8C0009").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("DA342E").unwrap(),
                        on_error_container: Color::hex("FFFFFF").unwrap(),
                        background: Color::hex("FFF9EB").unwrap(),
                        on_background: Color::hex("1D1C13").unwrap(),
                        surface: Color::hex("FFF9EB").unwrap(),
                        on_surface: Color::hex("1D1C13").unwrap(),
                        surface_variant: Color::hex("E8E2D0").unwrap(),
                        on_surface_variant: Color::hex("464336").unwrap(),
                        outline: Color::hex("625F51").unwrap(),
                        outline_variant: Color::hex("7F7B6B").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("323027").unwrap(),
                        inverse_on_surface: Color::hex("F6F0E3").unwrap(),
                        inverse_primary: Color::hex("D5C871").unwrap(),
                        primary_fixed: Color::hex("807628").unwrap(),
                        on_primary_fixed: Color::hex("FFFFFF").unwrap(),
                        primary_fixed_dim: Color::hex("665D0F").unwrap(),
                        on_primary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed: Color::hex("25808C").unwrap(),
                        on_secondary_fixed: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed_dim: Color::hex("006671").unwrap(),
                        on_secondary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed: Color::hex("577D67").unwrap(),
                        on_tertiary_fixed: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed_dim: Color::hex("3E644F").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        surface_dim: Color::hex("DFDACC").unwrap(),
                        surface_bright: Color::hex("FFF9EB").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("F9F3E5").unwrap(),
                        surface_container: Color::hex("F3EDE0").unwrap(),
                        surface_container_high: Color::hex("EDE8DA").unwrap(),
                        surface_container_highest: Color::hex("E7E2D5").unwrap(),
                    },
                    high_contrast: SchemeColors {
                        primary: Color::hex("272200").unwrap(),
                        on_primary: Color::hex("FFFFFF").unwrap(),
                        primary_container: Color::hex("4B4300").unwrap(),
                        on_primary_container: Color::hex("FFFFFF").unwrap(),
                        secondary: Color::hex("00272C").unwrap(),
                        on_secondary: Color::hex("FFFFFF").unwrap(),
                        secondary_container: Color::hex("004A53").unwrap(),
                        on_secondary_container: Color::hex("FFFFFF").unwrap(),
                        tertiary: Color::hex("002818").unwrap(),
                        on_tertiary: Color::hex("FFFFFF").unwrap(),
                        tertiary_container: Color::hex("254A37").unwrap(),
                        on_tertiary_container: Color::hex("FFFFFF").unwrap(),
                        error: Color::hex("4E0002").unwrap(),
                        on_error: Color::hex("FFFFFF").unwrap(),
                        error_container: Color::hex("8C0009").unwrap(),
                        on_error_container: Color::hex("FFFFFF").unwrap(),
                        background: Color::hex("FFF9EB").unwrap(),
                        on_background: Color::hex("1D1C13").unwrap(),
                        surface: Color::hex("FFF9EB").unwrap(),
                        on_surface: Color::hex("000000").unwrap(),
                        surface_variant: Color::hex("E8E2D0").unwrap(),
                        on_surface_variant: Color::hex("262418").unwrap(),
                        outline: Color::hex("464336").unwrap(),
                        outline_variant: Color::hex("464336").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("323027").unwrap(),
                        inverse_on_surface: Color::hex("FFFFFF").unwrap(),
                        inverse_primary: Color::hex("FCEE92").unwrap(),
                        primary_fixed: Color::hex("4B4300").unwrap(),
                        on_primary_fixed: Color::hex("FFFFFF").unwrap(),
                        primary_fixed_dim: Color::hex("332D00").unwrap(),
                        on_primary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed: Color::hex("004A53").unwrap(),
                        on_secondary_fixed: Color::hex("FFFFFF").unwrap(),
                        secondary_fixed_dim: Color::hex("003238").unwrap(),
                        on_secondary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed: Color::hex("254A37").unwrap(),
                        on_tertiary_fixed: Color::hex("FFFFFF").unwrap(),
                        tertiary_fixed_dim: Color::hex("0C3322").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("FFFFFF").unwrap(),
                        surface_dim: Color::hex("DFDACC").unwrap(),
                        surface_bright: Color::hex("FFF9EB").unwrap(),
                        surface_container_lowest: Color::hex("FFFFFF").unwrap(),
                        surface_container_low: Color::hex("F9F3E5").unwrap(),
                        surface_container: Color::hex("F3EDE0").unwrap(),
                        surface_container_high: Color::hex("EDE8DA").unwrap(),
                        surface_container_highest: Color::hex("E7E2D5").unwrap(),
                    },
                },
                dark: ColorScheme {
                    colors: SchemeColors {
                        primary: Color::hex("D5C871").unwrap(),
                        on_primary: Color::hex("373100").unwrap(),
                        primary_container: Color::hex("504700").unwrap(),
                        on_primary_container: Color::hex("F2E48A").unwrap(),
                        secondary: Color::hex("82D3E0").unwrap(),
                        on_secondary: Color::hex("00363D").unwrap(),
                        secondary_container: Color::hex("004F58").unwrap(),
                        on_secondary_container: Color::hex("9EEFFD").unwrap(),
                        tertiary: Color::hex("A7D0B7").unwrap(),
                        on_tertiary: Color::hex("113725").unwrap(),
                        tertiary_container: Color::hex("294E3B").unwrap(),
                        on_tertiary_container: Color::hex("C3ECD2").unwrap(),
                        error: Color::hex("FFB4AB").unwrap(),
                        on_error: Color::hex("690005").unwrap(),
                        error_container: Color::hex("93000A").unwrap(),
                        on_error_container: Color::hex("FFDAD6").unwrap(),
                        background: Color::hex("15130C").unwrap(),
                        on_background: Color::hex("E7E2D5").unwrap(),
                        surface: Color::hex("15130C").unwrap(),
                        on_surface: Color::hex("E7E2D5").unwrap(),
                        surface_variant: Color::hex("4A4739").unwrap(),
                        on_surface_variant: Color::hex("CCC6B5").unwrap(),
                        outline: Color::hex("959181").unwrap(),
                        outline_variant: Color::hex("4A4739").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("E7E2D5").unwrap(),
                        inverse_on_surface: Color::hex("323027").unwrap(),
                        inverse_primary: Color::hex("695F12").unwrap(),
                        primary_fixed: Color::hex("F2E48A").unwrap(),
                        on_primary_fixed: Color::hex("201C00").unwrap(),
                        primary_fixed_dim: Color::hex("D5C871").unwrap(),
                        on_primary_fixed_variant: Color::hex("504700").unwrap(),
                        secondary_fixed: Color::hex("9EEFFD").unwrap(),
                        on_secondary_fixed: Color::hex("001F24").unwrap(),
                        secondary_fixed_dim: Color::hex("82D3E0").unwrap(),
                        on_secondary_fixed_variant: Color::hex("004F58").unwrap(),
                        tertiary_fixed: Color::hex("C3ECD2").unwrap(),
                        on_tertiary_fixed: Color::hex("002113").unwrap(),
                        tertiary_fixed_dim: Color::hex("A7D0B7").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("294E3B").unwrap(),
                        surface_dim: Color::hex("15130C").unwrap(),
                        surface_bright: Color::hex("3B3930").unwrap(),
                        surface_container_lowest: Color::hex("100E07").unwrap(),
                        surface_container_low: Color::hex("1D1C13").unwrap(),
                        surface_container: Color::hex("212017").unwrap(),
                        surface_container_high: Color::hex("2C2A21").unwrap(),
                        surface_container_highest: Color::hex("37352C").unwrap(),
                    },
                    medium_contrast: SchemeColors {
                        primary: Color::hex("DACC75").unwrap(),
                        on_primary: Color::hex("1A1600").unwrap(),
                        primary_container: Color::hex("9D9241").unwrap(),
                        on_primary_container: Color::hex("000000").unwrap(),
                        secondary: Color::hex("86D7E5").unwrap(),
                        on_secondary: Color::hex("001A1D").unwrap(),
                        secondary_container: Color::hex("499CA9").unwrap(),
                        on_secondary_container: Color::hex("000000").unwrap(),
                        tertiary: Color::hex("ABD4BB").unwrap(),
                        on_tertiary: Color::hex("001B0E").unwrap(),
                        tertiary_container: Color::hex("729982").unwrap(),
                        on_tertiary_container: Color::hex("000000").unwrap(),
                        error: Color::hex("FFBAB1").unwrap(),
                        on_error: Color::hex("370001").unwrap(),
                        error_container: Color::hex("FF5449").unwrap(),
                        on_error_container: Color::hex("000000").unwrap(),
                        background: Color::hex("15130C").unwrap(),
                        on_background: Color::hex("E7E2D5").unwrap(),
                        surface: Color::hex("15130C").unwrap(),
                        on_surface: Color::hex("FFFAF3").unwrap(),
                        surface_variant: Color::hex("4A4739").unwrap(),
                        on_surface_variant: Color::hex("D0CBB9").unwrap(),
                        outline: Color::hex("A7A392").unwrap(),
                        outline_variant: Color::hex("878373").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("E7E2D5").unwrap(),
                        inverse_on_surface: Color::hex("2C2A21").unwrap(),
                        inverse_primary: Color::hex("514800").unwrap(),
                        primary_fixed: Color::hex("F2E48A").unwrap(),
                        on_primary_fixed: Color::hex("141100").unwrap(),
                        primary_fixed_dim: Color::hex("D5C871").unwrap(),
                        on_primary_fixed_variant: Color::hex("3D3700").unwrap(),
                        secondary_fixed: Color::hex("9EEFFD").unwrap(),
                        on_secondary_fixed: Color::hex("001417").unwrap(),
                        secondary_fixed_dim: Color::hex("82D3E0").unwrap(),
                        on_secondary_fixed_variant: Color::hex("003C44").unwrap(),
                        tertiary_fixed: Color::hex("C3ECD2").unwrap(),
                        on_tertiary_fixed: Color::hex("00150A").unwrap(),
                        tertiary_fixed_dim: Color::hex("A7D0B7").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("183D2B").unwrap(),
                        surface_dim: Color::hex("15130C").unwrap(),
                        surface_bright: Color::hex("3B3930").unwrap(),
                        surface_container_lowest: Color::hex("100E07").unwrap(),
                        surface_container_low: Color::hex("1D1C13").unwrap(),
                        surface_container: Color::hex("212017").unwrap(),
                        surface_container_high: Color::hex("2C2A21").unwrap(),
                        surface_container_highest: Color::hex("37352C").unwrap(),
                    },
                    high_contrast: SchemeColors {
                        primary: Color::hex("FFFAF3").unwrap(),
                        on_primary: Color::hex("000000").unwrap(),
                        primary_container: Color::hex("DACC75").unwrap(),
                        on_primary_container: Color::hex("000000").unwrap(),
                        secondary: Color::hex("F1FDFF").unwrap(),
                        on_secondary: Color::hex("000000").unwrap(),
                        secondary_container: Color::hex("86D7E5").unwrap(),
                        on_secondary_container: Color::hex("000000").unwrap(),
                        tertiary: Color::hex("EEFFF2").unwrap(),
                        on_tertiary: Color::hex("000000").unwrap(),
                        tertiary_container: Color::hex("ABD4BB").unwrap(),
                        on_tertiary_container: Color::hex("000000").unwrap(),
                        error: Color::hex("FFF9F9").unwrap(),
                        on_error: Color::hex("000000").unwrap(),
                        error_container: Color::hex("FFBAB1").unwrap(),
                        on_error_container: Color::hex("000000").unwrap(),
                        background: Color::hex("15130C").unwrap(),
                        on_background: Color::hex("E7E2D5").unwrap(),
                        surface: Color::hex("15130C").unwrap(),
                        on_surface: Color::hex("FFFFFF").unwrap(),
                        surface_variant: Color::hex("4A4739").unwrap(),
                        on_surface_variant: Color::hex("FFFAF3").unwrap(),
                        outline: Color::hex("D0CBB9").unwrap(),
                        outline_variant: Color::hex("D0CBB9").unwrap(),
                        shadow: Color::hex("000000").unwrap(),
                        scrim: Color::hex("000000").unwrap(),
                        inverse_surface: Color::hex("E7E2D5").unwrap(),
                        inverse_on_surface: Color::hex("000000").unwrap(),
                        inverse_primary: Color::hex("302A00").unwrap(),
                        primary_fixed: Color::hex("F7E88E").unwrap(),
                        on_primary_fixed: Color::hex("000000").unwrap(),
                        primary_fixed_dim: Color::hex("DACC75").unwrap(),
                        on_primary_fixed_variant: Color::hex("1A1600").unwrap(),
                        secondary_fixed: Color::hex("AAF3FF").unwrap(),
                        on_secondary_fixed: Color::hex("000000").unwrap(),
                        secondary_fixed_dim: Color::hex("86D7E5").unwrap(),
                        on_secondary_fixed_variant: Color::hex("001A1D").unwrap(),
                        tertiary_fixed: Color::hex("C7F1D6").unwrap(),
                        on_tertiary_fixed: Color::hex("000000").unwrap(),
                        tertiary_fixed_dim: Color::hex("ABD4BB").unwrap(),
                        on_tertiary_fixed_variant: Color::hex("001B0E").unwrap(),
                        surface_dim: Color::hex("15130C").unwrap(),
                        surface_bright: Color::hex("3B3930").unwrap(),
                        surface_container_lowest: Color::hex("100E07").unwrap(),
                        surface_container_low: Color::hex("1D1C13").unwrap(),
                        surface_container: Color::hex("212017").unwrap(),
                        surface_container_high: Color::hex("2C2A21").unwrap(),
                        surface_container_highest: Color::hex("37352C").unwrap(),
                    },
                },
            },
            palettes: ColorPalettes {
                primary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("141100").unwrap(),
                    p_10: Color::hex("201C00").unwrap(),
                    p_15: Color::hex("2B2600").unwrap(),
                    p_20: Color::hex("373100").unwrap(),
                    p_25: Color::hex("433C00").unwrap(),
                    p_30: Color::hex("504700").unwrap(),
                    p_35: Color::hex("5D5300").unwrap(),
                    p_40: Color::hex("695F09").unwrap(),
                    p_50: Color::hex("837824").unwrap(),
                    p_60: Color::hex("9E923B").unwrap(),
                    p_70: Color::hex("BAAD53").unwrap(),
                    p_80: Color::hex("D6C86B").unwrap(),
                    p_90: Color::hex("F3E484").unwrap(),
                    p_95: Color::hex("FFF2A5").unwrap(),
                    p_98: Color::hex("FFF9E9").unwrap(),
                    p_99: Color::hex("FFFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                secondary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("111111").unwrap(),
                    p_10: Color::hex("1C1B1B").unwrap(),
                    p_15: Color::hex("262626").unwrap(),
                    p_20: Color::hex("313030").unwrap(),
                    p_25: Color::hex("3C3B3B").unwrap(),
                    p_30: Color::hex("474746").unwrap(),
                    p_35: Color::hex("535252").unwrap(),
                    p_40: Color::hex("5F5E5E").unwrap(),
                    p_50: Color::hex("787776").unwrap(),
                    p_60: Color::hex("929090").unwrap(),
                    p_70: Color::hex("ADABAA").unwrap(),
                    p_80: Color::hex("C8C6C5").unwrap(),
                    p_90: Color::hex("E5E2E1").unwrap(),
                    p_95: Color::hex("F3F0EF").unwrap(),
                    p_98: Color::hex("FCF9F8").unwrap(),
                    p_99: Color::hex("FFFBFB").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                tertiary: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("00150A").unwrap(),
                    p_10: Color::hex("052014").unwrap(),
                    p_15: Color::hex("102B1E").unwrap(),
                    p_20: Color::hex("1B3628").unwrap(),
                    p_25: Color::hex("264132").unwrap(),
                    p_30: Color::hex("324C3D").unwrap(),
                    p_35: Color::hex("3D5849").unwrap(),
                    p_40: Color::hex("496454").unwrap(),
                    p_50: Color::hex("617D6C").unwrap(),
                    p_60: Color::hex("7A9785").unwrap(),
                    p_70: Color::hex("95B29F").unwrap(),
                    p_80: Color::hex("AFCEBA").unwrap(),
                    p_90: Color::hex("CBEAD5").unwrap(),
                    p_95: Color::hex("D9F8E3").unwrap(),
                    p_98: Color::hex("E8FFEF").unwrap(),
                    p_99: Color::hex("F4FFF5").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                neutral: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("111111").unwrap(),
                    p_10: Color::hex("1C1B1B").unwrap(),
                    p_15: Color::hex("262625").unwrap(),
                    p_20: Color::hex("313030").unwrap(),
                    p_25: Color::hex("3C3B3B").unwrap(),
                    p_30: Color::hex("484646").unwrap(),
                    p_35: Color::hex("535252").unwrap(),
                    p_40: Color::hex("5F5E5E").unwrap(),
                    p_50: Color::hex("787776").unwrap(),
                    p_60: Color::hex("929090").unwrap(),
                    p_70: Color::hex("ADAAAA").unwrap(),
                    p_80: Color::hex("C9C6C5").unwrap(),
                    p_90: Color::hex("E5E2E1").unwrap(),
                    p_95: Color::hex("F4F0EF").unwrap(),
                    p_98: Color::hex("FCF8F8").unwrap(),
                    p_99: Color::hex("F9FDFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
                neutral_variant: ColorPalette {
                    p_0: Color::hex("000000").unwrap(),
                    p_5: Color::hex("121109").unwrap(),
                    p_10: Color::hex("1D1C13").unwrap(),
                    p_15: Color::hex("28261D").unwrap(),
                    p_20: Color::hex("333027").unwrap(),
                    p_25: Color::hex("3E3B31").unwrap(),
                    p_30: Color::hex("49473C").unwrap(),
                    p_35: Color::hex("555248").unwrap(),
                    p_40: Color::hex("615E53").unwrap(),
                    p_50: Color::hex("7A776B").unwrap(),
                    p_60: Color::hex("949184").unwrap(),
                    p_70: Color::hex("AFAB9E").unwrap(),
                    p_80: Color::hex("CBC6B8").unwrap(),
                    p_90: Color::hex("E8E2D4").unwrap(),
                    p_95: Color::hex("F6F0E2").unwrap(),
                    p_98: Color::hex("FFF9EA").unwrap(),
                    p_99: Color::hex("FFFBFF").unwrap(),
                    p_100: Color::hex("FFFFFF").unwrap(),
                },
            },
        }
    }
}
